FROM debian

MAINTAINER flbeaumo <flbeaumo@student.42.fr>

RUN apt-get update
RUN apt-get install -y apt-utils build-essential \
	net-tools wget curl openssh-server \
	vim git nmap valgrind

CMD bash
